{% set version = "2.4.0" %}

package:
  name: esda
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/esda/esda-{{ version }}.tar.gz
  sha256: 440d2b9343485a042768821aa5dbc3ec51ca6eb8ced69872efbf0a61f0af10ed

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >3.4
    - pip
  run:
    - python >3.4
    - libpysal
    - pandas
    - scikit-learn
    - scipy >=0.11

test:
  imports:
    - esda
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pysal/esda
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Exploratory Spatial Data Analysis

extra:
  recipe-maintainers:
    - ocefpaf
