{% set python_min = "3.11" %}
{% set version = "2.8.1" %}

package:
  name: esda
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/esda/esda-{{ version }}.tar.gz
  sha256: 26ae1bff2697a0ded41d9bb590664cb24047467457820b44f52a1ddec353292f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - geopandas >=0.14
    - libpysal >=4.12
    - numpy >=1.26
    - pandas >2.1
    - scikit-learn >=1.4
    - scipy >=1.12
    - shapely >=2.1

test:
  imports:
    - esda
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pysal/esda
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Exploratory Spatial Data Analysis

extra:
  recipe-maintainers:
    - knaaptime
    - martinfleis
    - jGaboardi
    - ocefpaf
