{% set python_min = "3.10" %}
{% set version = "2.7.0" %}

package:
  name: esda
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/esda/esda-{{ version }}.tar.gz
  sha256: e3167aa1f010a377c5b4b457ea6f91d126816a1070fa48a4e048e9f8633082f5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - geopandas >=0.12
    - libpysal >=4.12
    - numpy >=1.24
    - pandas >1.5
    - scikit-learn >=1.2
    - scipy >=1.9
    - shapely >=2.0

test:
  imports:
    - esda
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pysal/esda
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Exploratory Spatial Data Analysis

extra:
  recipe-maintainers:
    - knaaptime
    - martinfleis
    - jGaboardi
    - ocefpaf
