{% set version = "2.1.0" %}

package:
  name: esda
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/esda/esda-{{ version }}.tar.gz
  sha256: f5e7299c061fba430cb716039b5319a30b45edb34c426482bfec6648323d8570

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >3.4
    - pip
  run:
    - python >3.4
    - libpysal
    - numpy
    - scipy

test:
  imports:
    - esda
  requires:
    - nose

about:
  home: https://github.com/pysal/esda
  license: BSD-3-Clause
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Package with statistics for exploratory spatial data analysis

extra:
  recipe-maintainers:
    - ocefpaf
