{% set version = "2.3.0" %}

package:
  name: esda
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/esda/esda-{{ version }}.tar.gz
  sha256: 70def8ff4f571e14e8c9bce669de2d02bbfc336d7d31eb7d942d17ddda3dd9ac

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >3.4
    - pip
  run:
    - python >3.4
    - libpysal
    - numpy
    - scipy >=0.11
    - scikit-learn

test:
  imports:
    - esda

about:
  home: https://github.com/pysal/esda
  license: BSD-3-Clause
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Package with statistics for exploratory spatial data analysis

extra:
  recipe-maintainers:
    - ocefpaf
